---
kind: pipeline
name: default

steps:  
  - name: cleanup
    image: docker
    commands:
      - docker system prune --volumes -f -a
      - docker mcr.microsoft.com/dotnet/aspnet:5.0.0-buster-slim
      - docker mcr.microsoft.com/dotnet/sdk:5.0.102-ca-patch-buster-slim
      - docker buildkite/puppeteer:5.2.1
    volumes:
      - name: docker1
        path: /var/run/docker.sock
      - name: docker2
        path: /var/lib/docker
      
volumes:
  - name: build
    temp: {}
  - name: release
    temp: {}
  - name: docker1
    host:
      path: /var/run/docker.sock
  - name: docker2
    host:
      path: /var/lib/docker
