---
kind: pipeline
name: default

steps:  
  - name: cleanup
    image: docker
    commands:
      - docker system prune --volumes -f -a
      - docker pull mcr.microsoft.com/dotnet/core/sdk:3.1-buster
      - docker pull mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim
    volumes:
      - name: docker1
        path: /var/run/docker.sock
      - name: docker2
        path: /var/lib/docker
      
volumes:
  - name: build
    temp: {}
  - name: release
    temp: {}
  - name: docker1
    host:
      path: /var/run/docker.sock
  - name: docker2
    host:
      path: /var/lib/docker
